# docker network create personal-net
version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    networks:
      - personal-net
    ports: 
      - 27017:27017
    volumes: 
      - mongodbdata:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - personal-net
    ports: 
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
  
  krakend_ce:
    image: devopsfaith/krakend:1.4.1
    container_name: krakend
    command: run -d -c /etc/krakend/krakend.json
    volumes:
      - ./krakend:/etc/krakend
    networks:
      - personal-net
    ports:
      - "8080:8080"
      - "1234:1234"
      - "8090:8090"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9090:8080
    networks:
      - personal-net
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - personal-net
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

volumes: 
  mongodbdata:
  rabbitmqdata:

networks:
  personal-net:
    external: true